[[colophon]]
[colophon]
== Appendix: Colophon

Almost all of the software that I have used in the creation of this book are <<floss,FLOSS>>.

=== Birth of the Book

In the first draft of this book, I had used Red Hat 9.0 Linux as the foundation of my setup and in
the sixth draft, I used Fedora Core 3 Linux as the basis of my setup.

Initially, I was using KWord to write the book (as explained in the <<history_lesson,history
lesson>> in the preface).

=== Teenage Years

Later, I switched to DocBook XML using Kate but I found it too tedious. So, I switched to
OpenOffice which was just excellent with the level of control it provided for formatting as well as
the PDF generation, but it produced very sloppy HTML from the document.

Finally, I discovered XEmacs and I rewrote the book from scratch in DocBook XML (again) after I
decided that this format was the long term solution.

In the sixth draft, I decided to use Quanta+ to do all the editing. The standard XSL stylesheets
that came with Fedora Core 3 Linux were being used. However, I had written a CSS document to give
color and style to the HTML pages. I had also written a crude lexical analyzer, in Python of
course, which automatically provides syntax highlighting to all the program listings.

For the seventh draft, I'm using http://www.mediawiki.org[MediaWiki] as the basis of my setup. I
used to edit everything online and the readers can directly read/edit/discuss within the wiki
website, but I ended up spending more time fighting spam than writing.

For the eight draft, I used http://www.swaroopch.com/notes/vim[Vim],
http://johnmacfarlane.net/pandoc/README.html[Pandoc], and Mac OS X.

=== Now

For the ninth draft, I switched to http://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc format]
and used http://www.masteringemacs.org/articles/2013/03/11/whats-new-emacs-24-3/[Emacs 24.3],
https://github.com/chriskempson/tomorrow-theme[tomorrow theme],
https://www.mozilla.org/en-US/styleguide/products/firefox-os/typeface/#download-primary[Fira Mono
font] and https://github.com/sensorflo/adoc-mode/wiki[adoc-mode] to write.

=== About the Author

See http://swaroopch.com/about/
