[[floss]]
== Appendix: FLOSS

NOTE: Please note that this section was written in 2003, so some of this might sound quaint to you
:-)

"Free/Libre and Open Source Software", in short, http://en.wikipedia.org/wiki/FLOSS[FLOSS] is based
on the concept of a community, which itself is based on the concept of sharing, and particularly
the sharing of knowledge. FLOSS are free for usage, modification and redistribution.

If you have already read this book, then you are already familiar with FLOSS since you have been
using *Python* all along and Python is an open source software!

Here are some examples of FLOSS to give an idea of the kind of things that community sharing and
building can create:

http://www.kernel.org[Linux] ::
This is a FLOSS OS kernel used in the GNU/Linux operating system. Linux, the kernel, was started by
Linus Torvalds as a student. Android is based on Linux. Any website you use these days will mostly
be running on Linux.

http://www.ubuntu.com[Ubuntu] ::
This is a community-driven distribution, sponsored by Canonical and it is the most popular
GNU/Linux distribution today. It allows you to install a plethora of FLOSS available and all this
in an easy-to-use and easy-to-install manner. Best of all, you can just reboot your computer and
run GNU/Linux off the CD! This allows you to completely try out the new OS before installing it on
your computer. However, Ubuntu is not entirely free software; it contains proprietary drivers,
firmware, and applications.

http://www.libreoffice.org/[LibreOffice] ::
This is an excellent community-driven and developed office suite with a writer, presentation,
spreadsheet and drawing components among other things. It can even open and edit MS Word and MS
PowerPoint files with ease. It runs on almost all platforms and is entirely free, libre and open
source software.

http://www.mozilla.org/products/firefox[Mozilla Firefox] ::
This is _the_ best web browser. It is blazingly fast and has gained critical acclaim for its
sensible and impressive features. The extensions concept allows any kind of plugins to be used.

http://www.mono-project.com[Mono] ::
This is an open source implementation of the Microsoft .NET platform.  It allows .NET applications
to be created and run on GNU/Linux, Windows, FreeBSD, Mac OS and many other platforms as well.

http://httpd.apache.org[Apache web server] ::

This is the popular open source web server. In fact, it is _the_ most popular web server on the
planet! It runs nearly more than half of the websites out there. Yes, that's right - Apache handles
more websites than all the competition (including Microsoft IIS) combined.

http://www.videolan.org/vlc/[VLC Player] ::
This is a video player that can play anything from DivX to MP3 to Ogg to VCDs and DVDs to ... who
says open source ain't fun? ;-)

This list is just intended to give you a brief idea - there are many more excellent FLOSS out
there, such as the Perl language, PHP language, Drupal content management system for websites,
PostgreSQL database server, TORCS racing game, KDevelop IDE, Xine - the movie player, VIM editor,
Quanta+ editor, Banshee audio player, GIMP image editing program, ... This list could go on
forever.

To get the latest buzz in the FLOSS world, check out the following websites:

- http://www.omgubuntu.co.uk/[OMG! Ubuntu!]
- http://www.webupd8.org/[Web Upd8]
- http://www.distrowatch.com[DistroWatch]
- http://planet.debian.org/[Planet Debian]

Visit the following websites for more information on FLOSS:

- http://github.com/explore[GitHub Explore]
- http://www.codetriage.com/[Code Triage]
- http://www.sourceforge.net[SourceForge]
- http://www.freshmeat.net[FreshMeat]

So, go ahead and explore the vast, free and open world of FLOSS!
