[[frontpage]]
==  Welcome

//////////////////////////////////////////////////
This book is written for Python 2 series, even though Python 3 series is the latest. You can read
more about why in the <<python2vs3,Python 2 vs. 3>> section.
//////////////////////////////////////////////////

[[who_reads_bop]]
=== Who reads A Byte of Python?

Here are what people are saying about the book:

[quote,'mailto:wmich50@theramp.net[Walt Michalik]']
__________________________________________________
This is the best beginner's tutorial I've ever seen! Thank you for your effort.
__________________________________________________

[quote,'mailto:joshrob@poczta.onet.pl[Joshua Robin]']
__________________________________________________
The best thing i found was "A Byte of Python", which is simply a brilliant book for a
beginner. It's well written, the concepts are well explained with self evident examples.
__________________________________________________

[quote,'https://twitter.com/ShanRajasekaran/status/268910645842423809[Shan Rajasekaran]']
__________________________________________________
Excellent gentle introduction to programming #Python for beginners
__________________________________________________

[quote,'https://twitter.com/nickaigi/status/175508815729541120[Nickson Kaigi]']
__________________________________________________
Best newbie guide to python
__________________________________________________

[quote,'https://twitter.com/HerbertFeutl/status/11901471389913088[Herbert Feutl]']
__________________________________________________
start to love python with every single page read
__________________________________________________

[quote,'https://twitter.com/Dili_mathilakam/status/220033783066411008[Dilip]']
__________________________________________________
perfect beginners guide for python, will give u key to unlock magical world of python
__________________________________________________

[quote,'https://twitter.com/BiologistJohn/statuses/194726001803132928[Biologist John]']
__________________________________________________
I should be doing my actual "work" but just found "A Byte of Python". A great guide with great
examples.
__________________________________________________

[quote,'https://twitter.com/mangeshnanoti/status/225680668867321857[Mangesh]']
__________________________________________________
Recently started reading a Byte of python. Awesome work. And that too for free. Highly recommended
for aspiring pythonistas.
__________________________________________________

[quote,'http://apas.gr/2010/04/27/learning-python/[Apostolos]']
__________________________________________________
A Byte of Python, written by Swaroop. (this is the book I'm currently reading). Probably the best
to start with, and probably the best in the world for every newbie or even a more experienced user.
__________________________________________________

[quote,Franklin]
__________________________________________________
Thank you so much for writing A Byte Of Python. I just started learning how to code two days ago
and I'm already building some simple games. Your guide has been a dream and I just wanted to let
you know how valuable it has been.
__________________________________________________

[quote,Madhura]
__________________________________________________
I'm from Dayanandasagar College of Engineering (7th sem, CSE). Firstly i want to say that your book
"The byte of python" is too good a book for a beginner in python like me.The concepts are so well
explained with simple examples that helped me to easily learn python. Thank you so much.
__________________________________________________

[quote,Matt]
__________________________________________________
I am a 18 year old IT student studying at University in Ireland. I would like to express my
gratitude to you for writing your book "A Byte of Python", I already had knowledge of 3 programming
langagues - C, Java and Javascript, and Python was by far the easiest langague I have ever learned,
and that was mainly because your book was fantastic and made learning python very simple and
interesting. It is one of the best written and easy to follow programming books I have ever
read. Congratulations and keep up the great work.
__________________________________________________

[quote,'mailto:pavel.simo@gmail.com[Pavel Simo]']
__________________________________________________
Hi, I'm from Dominican Republic. My name is Pavel, recently I read your book _A Byte of Python_ and
I consider it excellent!!  :). I learnt much from all the examples. Your book is of great help for
newbies like me...
__________________________________________________

[quote,Roy Lau]
__________________________________________________
I am a student from China, Now ,I have read you book A byte of Python, Oh it's beautiful. The book
is very simple but can help all the first learnners. You know I am interesting in Java and cloud
computing many times, i have to coding programm for the server, so i think python is a good choice,
finish your book, i think its not only a good choice its must use the Python. My English is not
very well, the email to you, i just wanna thank you! Best Wishes for you and your family.
__________________________________________________

[quote,'mailto:sy137@gmail.com[Samuel Young]']
__________________________________________________
I recently finished reading Byte of Python, and I thought I really ought to thank you. I was very
sad to reach the final pages as I now have to go back to dull, tedious oreilly or etc.  manuals for
learning about python. Anyway, I really appreciate your book.
__________________________________________________

[quote,'mailto:jduarte1@cfl.rr.com[Joseph Duarte]']
__________________________________________________
Dear Swaroop, I am taking a class from an instructor that has no interest in teaching. We are using
Learning Python, second edition, by O'Reilly. It is not a text for beginner without any programming
knowledge, and an instructor that should be working in another field.  Thank you very much for your
book, without it I would be clueless about Python and programming. Thanks a million, you are able
to _break the message down_ to a level that beginners can understand and not everyone can.
__________________________________________________

[quote,Chris-André Sommerseth]
__________________________________________________
I love your book! It is the greatest Python tutorial ever, and a very useful reference. Brilliant,
a true masterpiece! Keep up the good work!
__________________________________________________

[quote,'mailto:m_gallivan12@hotmail.com[Matt Gallivan]']
__________________________________________________
I'm just e-mailing you to thank you for writing Byte of Python online.  I had been attempting
Python for a few months prior to stumbling across your book, and although I made limited success
with pyGame, I never completed a program.

Thanks to your simplification of the categories, Python actually seems a reachable goal. It seems
like I have finally learned the foundations and I can continue into my real goal, game development.

...

Once again, thanks VERY much for placing such a structured and helpful guide to basic programming
on the web.  It shoved me into and out of OOP with an understanding where two text books had
failed.
__________________________________________________

[quote,'mailto:sedo_91@hotmail.com[Ahmed Mohammed]']
__________________________________________________
I would like to thank you for your book _A Byte of Python_ which i myself find the best way to
learn python. I am a 15 year old i live in egypt my name is Ahmed. Python was my second programming
language i learn visual basic 6 at school but didn't enjoy it, however i really enjoyed learning
python. I made the addressbook program and i was sucessful. i will try to start make more programs
and read python programs (if you could tell me source that would be helpful). I will also start on
learning java and if you can tell me where to find a tutorial as good as yours for java that would
help me a lot. Thanx.
__________________________________________________

[quote,'http://www.linux.com/feature/126522[Drew Ames]']
__________________________________________________
A wonderful resource for beginners wanting to learn more about Python is the 110-page PDF tutorial
A Byte of Python by Swaroop C H. It is well-written, easy to follow, and may be the best
introduction to Python programming available.
__________________________________________________

[quote,'http://paxmodept.com/telesto/blogitem.htm?id=627[Jason Delport]']
__________________________________________________
Yesterday I got through most of Byte of Python on my Nokia N800 and it's the easiest and most
concise introduction to Python I have yet encountered. Highly recommended as a starting point for
learning Python.
__________________________________________________

[quote,'http://twitter.com/suren/status/12840485454[Surendran]']
__________________________________________________
Byte of Vim and Python by @swaroopch is by far the best works in technical writing to me. Excellent
reads #FeelGoodFactor
__________________________________________________

[quote,'http://www.facebook.com/pythonlang/posts/406873916788[Justin LoveTrue]']
__________________________________________________
"Byte of python" best one by far man

(in response to the question "Can anyone suggest a good, inexpensive resource for learning the
basics of Python? ")
__________________________________________________

[quote,'https://twitter.com/a_chinmay/status/258822633741762560[Chinmay]']
__________________________________________________
The Book Byte of python was very helpful ..Thanks bigtime :)
__________________________________________________

[quote,'http://stackoverflow.com/a/457785/4869[Patrick Harrington]']
__________________________________________________
Always been a fan of A Byte of Python - made for both new and experienced programmers.
__________________________________________________

[quote,'https://twitter.com/Pagal_e_azam/statuses/242865885256232960[Gadadhari Bheem]']
__________________________________________________
I started learning python few days ago from your book..thanks for such a nice book. it is so well
written, you made my life easy..so you found a new fan of yours..thats me :) tons of thanks.
__________________________________________________

[quote,Bob]
__________________________________________________
Thank you ever so much for this book!!

This book cleared up many questions I had about certain aspects of Python such as object oriented
programming.

I do not feel like an expert at OO but I know this book helped me on a first step or two.

I have now written several python programs that actually do real things for me as a system
administrator. They are all procedural oriented but they are small by most peoples standards.

Again, thanks for this book. Thank you for having it on the web.
__________________________________________________

[quote,"The Walrus"]
__________________________________________________
I just want to thank you for writing the first book on programming I've ever really read. Python is
now my first language, and I can just imagine all the possibilities. So thank you for giving me the
tools to create things I never would have imagined I could do before.
__________________________________________________

[quote,Chris]
__________________________________________________
I wanted to thank you for writing _A Byte Of Python_ (2 & 3 Versions).  It has been invaluable to
my learning experience in Python & Programming in general.

Needless to say, I am a beginner in the programming world, a couple of months of self study up to
this point. I had been using youtube tutorials & some other online tutorials including other free
books. I decided to dig into your book yesterday, & I've learned more on the first few pages than
any other book or tutorial. A few things I had been confused about, were cleared right up with a
GREAT example & explanation. Can't wait to read (and learn) more!!

Thank you so much for not only writing the book, but for putting it under the creative commons
license (free). Thank goodness there are unselfish people like you out there to help & teach the
rest of us.
__________________________________________________

[quote,Nick]
__________________________________________________
I wrote you back in 2011 and I was just getting into Python and wanted to thank you for your
tutorial "A Byte of Python".  Without it, I would have fallen by the wayside.  Since then I have
gone on to program a number of functions in my organization with this language with yet more on the
horizon.  I would not call myself an advanced programmer by any stretch but I notice the occasional
request for assistance now from others since I started using it.  I discovered, while reading
"Byte" why I had ceased studying C and C\++ and it was because the book given to me started out with
an example containing an augmented assignment.  Of course, there was no explanation for this
arrangement of operators and I fell on my head trying to make sense of what was on the written
page.  As I recall it was a most frustrating exercise which I eventually abandoned. Doesn't mean C
or C++ is impossible to learn, or even that I am stupid, but it does mean that the documentation I
worked my way through did not define the symbols and words which is an essential part of any
instruction. Just as computers will not be able to understand a computer word or computer symbol
that is outside the syntax for the language being used, a student new to any field will not grasp
his subject if he encounters words or symbols for which there are no definitions.  You get a "blue
screen" as it were in either case.  The solution is simple, though: find the word or symbol and get
the proper definition or symbol and lo and behold,the computer or student can proceed.  Your book
was so well put together that I found very little in it I couldn't grasp.  So, thank you.  I
encourage you to continue to include full definitions of terms.  The documentation with Python is
good, once you know, (the examples are its strength from what I see) but in many cases it seems
that you have to know in order to understand the documentation which to my mind is not what
should be.  Third party tutorials express the need for clarification of the documentation and their
success largely depends on the words that are used to describe the terminology.  I have recommended
your book to many others. Some in Australia, some in the Caribbean and yet others in the US. It
fills a niche no others do.  I hope you are doing well and wish you all the success in the future.
__________________________________________________

[quote,Ankush]
__________________________________________________
hey, this is ankush(19). I was facing a great difficulty to start with python. I tried a lot of
books but all were bulkier and not target oriented; and then i found this lovely one, which made me
love python in no time. Thanks a lot for this "beautiful piece of book".
__________________________________________________

[quote,Luca]
__________________________________________________
I would like to thank you for your excellent guide on Python. I am a molecular biologist (with
little programming background) and for my work I need to handle big datasets of DNA sequences and
to analyse microscope images. For both things, programming in python has been useful, if not
essential to complete and publish a 6-years project.

That such a guide is freely available is a clear sign that the forces of evil are not yet ruling
the world! :)
__________________________________________________

[quote,'http://www.overclock.net/t/1177951/want-to-learn-programming-where-do-i-start#post_15837176["{Unregistered}"]']
__________________________________________________
Since this is going to be the first language you learn, you should use A Byte of Python. It really
gives a proper introduction into programming in Python and it is paced well enough for the average
beginner. The most important thing from then on will be actually starting to practice making your
own little programs.
__________________________________________________

[quote,Jocimar]
__________________________________________________
Just to say a loud and happy _thank you very much_ for publishing "A Byte of Python" and "A Byte of
Vim". Those books were very useful to me four or five years ago when I starting learning
programming. Right now I'm developing a project that was a dream for a long, long time and just
want to say _thank you_. Keep walking. You are a source of motivation. All the best.
__________________________________________________

[quote,Dattatray]
__________________________________________________
Finished reading A byte of Python in 3 days. It is thoroughly interesting. Not a single page was
boring. I want to understand the Orca screen reader code. Your book has hopefully equipped me
for it.
__________________________________________________

The book is even used by NASA! It is being used in their
http://dsnra.jpl.nasa.gov/software/Python/byte-of-python/output/byteofpython_html/[Jet Propulsion
Laboratory] with their Deep Space Network project.

=== Academic Courses

This book is/was being used as instructional material in various educational institutions:

- 'Principles of Programming Languages' course at
  http://www.few.vu.nl/~nsilvis/PPL/2007/index.html['Vrije Universiteit, Amsterdam']
- 'Basic Concepts of Computing' course at
  http://www.cs.ucdavis.edu/courses/exp_course_desc/10.html['University of California, Davis']
- 'Programming With Python' course at
  http://www.people.fas.harvard.edu/~preshman/python_winter.html['Harvard University']
- 'Introduction to Programming' course at http://www.comp.leeds.ac.uk/acom1900/['University of
  Leeds']
- 'Introduction to Application Programming' course at
  http://www.cs.bu.edu/courses/cs108/materials.html['Boston University']
- 'Information Technology Skills for Meteorology' course at
  http://gentry.metr.ou.edu/byteofpython/['University of Oklahoma']
- 'Geoprocessing' course at http://www.msu.edu/~ashton/classes/825/index.html['Michigan State
  University']
- 'Multi Agent Semantic Web Systems' course at the
  http://homepages.inf.ed.ac.uk/ewan/masws/['University of Edinburgh']
- 'Introduction to Computer Science and Programming' at
  http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00sc-introduction-to-computer-science-and-programming-spring-2011/references/['MIT
  OpenCourseWare']

=== License

This book is licensed under a http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons
Attribution-ShareAlike 4.0 International License].

This means:

- You are free to Share i.e. to copy, distribute and transmit this book
- You are free to Remix i.e. to make changes to this book (especially translations)
- You are free to use it for commercial purposes

Please note:

- Please do *not* sell electronic or printed copies of the book unless you have clearly and
  prominently mentioned in the description that these copies are *not* from the original author of
  this book.
- Attribution *must* be shown in the introductory description and front page of the document by
  linking back to {homepage} and clearly indicating that the original text can be fetched from this
  location.
- All the code/scripts provided in this book is licensed under the
  http://www.opensource.org/licenses/bsd-license.php[3-clause BSD License] unless otherwise noted.

=== Read Now

You can read the book online at {homepage}

=== Buy The Book

A printed hardcopy of the book can be purchased at {buy} for your offline reading pleasure, and to
support the continued development and improvement of this book.

=== Download

- http://files.swaroopch.com/python/byte_of_python.pdf[PDF]
- http://files.swaroopch.com/python/byte_of_python.epub[EPUB]
- https://github.com/swaroopch/byte_of_python[GitHub]

If you wish to support the continued development of this book, please consider
{buy}[buying a hardcopy].

=== Read the book in your native language

If you are interested in reading or contributing translations of this book to other human
languages, please see <<translations,Translations>>.
